apiVersion: v1
kind: Namespace
metadata:
  name: flowfirst
---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJmbG93Zmlyc3QuYXp1cmVjci5pbyI6eyJ1c2VybmFtZSI6ImZsb3dmaXJzdCIsInBhc3N3b3JkIjoidDhvc2lDQmpqc095aXhNcUZyQXc3RmxtSkhvWFNTZ0hSNStoTFB5YUZ6K0FDUkN2b3FIZyIsImF1dGgiOiJabXh2ZDJacGNuTjBPblE0YjNOcFEwSnFhbk5QZVdsNFRYRkdja0YzTjBac2JVcEliMWhUVTJkSVVqVXJhRXhRZVdGR2VpdEJRMUpEZG05eFNHYz0ifX19
kind: Secret
metadata:
  creationTimestamp: null
  name: acr-secret
  namespace: flowfirst
type: kubernetes.io/dockerconfigjson
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flowfirst-web
  namespace: flowfirst
  labels:
    app: flowfirst-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flowfirst-web
  template:
    metadata:
      labels:
        app: flowfirst-web
    spec:
      # If your image is in a private registry, uncomment imagePullSecrets
      # imagePullSecrets:
      #   - name: regcred
      imagePullSecrets:
        - name: acr-secret
      containers:
        - name: web
          image: flowfirst.azurecr.io/flowfirst/web:1.0.6
          imagePullPolicy: IfNotPresent

          ports:
            - name: http
              containerPort: 80

          # Nginx serves "/" so these probes are valid
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 3
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: flowfirst-web-svc
  namespace: flowfirst
  labels:
    app: flowfirst-web
spec:
  type: ClusterIP
  selector:
    app: flowfirst-web
  ports:
    - name: http
      port: 80
      targetPort: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flowfirst-web
  namespace: flowfirst
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - hosted.flowfirst.ai
    secretName: flowfirst-frontend-tls
  rules:
    - host: hosted.flowfirst.ai
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: flowfirst-web-svc
                port:
                  number: 80
---
# migration

apiVersion: v1
kind: Pod
metadata:
  name: migration
  namespace: flowfirst
spec:
  restartPolicy: Never
  imagePullSecrets:
    - name: acr-secret
  containers:
    - name: migration
      image: flowfirst.azurecr.io/flowfirst/migrations:latest
      command: ["/bin/sh","-c","sleep 360000"]
      stdin: true
      tty: true