secret:
  jwt:
    anonKey: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYW5vbiIsImlzcyI6InN1cGFiYXNlIiwiaWF0IjoxNzY3MDM0ODAwLCJleHAiOjE5MjQ4MDEyMDB9.3FzYb32-dv1XQE9U_AG1t662Uu15nF8NRoH0vAC6Pyk"
    serviceKey: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoic2VydmljZV9yb2xlIiwiaXNzIjoic3VwYWJhc2UiLCJpYXQiOjE3NjcwMzQ4MDAsImV4cCI6MTkyNDgwMTIwMH0.2xTMLxC8O7i0wskvG5cQ6ILwkoFR_5oOcWQ1Bn0DpSs"
    secret: "zZxVbxUUJtPLEkKGcV77HGMzuK8ANCUPqrKOg70V"
  smtp:
    username: your-mail@agentic.staging.floorzap.info
    password: example123456
  dashboard:
    username: admin
    password: admin
    openAiApiKey: api-key
  db:
    password: example123456
    database: postgres
  analytics:
    publicAccessToken: mL79jbAlfZDsfqJWbBQtFkZJfb241WW0
    privateAccessToken: 2Q2M2SlIorbgXlF/UiorQ35AqRAu80q6
  realtime:
    secretKeyBase: n7wZI92Jv0km5yF3hxaq0AsFmfvr0eqPQUHNUpwvyvb/+sE7WM/UjC1L0Wk2aX1u
  meta:
    cryptoKey: "ge7Y0I3z0zB+KIqMPzg6blLIsL9I9Ttx"
  s3:
    isValid: false
    keyId: "asdvajsd"
    accessKey: "asdbjahsbdjhasd"

db:
  enabled: true
  image:
    repository: supabase/postgres
    pullPolicy: IfNotPresent
    tag: 17.6.1.066
  livenessProbe:
    exec:
      command:
        - pg_isready
        - -U
        - postgres
    initialDelaySeconds: 3
  serviceAccount:
    create: true
  service:
    type: ClusterIP
    port: 5432
  autoscaling:
    enabled: false
  persistence:
    enabled: true
    storageClassName: "azuredisk-retain"
    annotations: {}
    size: 8Gi
    accessModes:
      - ReadWriteOnce
    class: ""

studio:
  enabled: true
  image:
    repository: supabase/studio
    pullPolicy: IfNotPresent
    tag: "latest"
  environment:
    DEFAULT_ORGANIZATION_NAME: Default Organization
    DEFAULT_PROJECT_NAME: Default Project
    SUPABASE_PUBLIC_URL: https://agentic.staging.floorzap.info
    NEXT_PUBLIC_ENABLE_LOGS: true
    SNIPPETS_MANAGEMENT_FOLDER: /var/lib/studio/snippets
  serviceAccount:
    create: true
  service:
    type: ClusterIP
    port: 9001
  autoscaling:
    enabled: false
  livenessProbe:
    tcpSocket:
      port: 3000
    initialDelaySeconds: 3

auth:
  enabled: true
  image:
    repository: supabase/gotrue
    pullPolicy: IfNotPresent
    tag: "v2.184.0"
  environment:
    API_EXTERNAL_URL: https://agentic.staging.floorzap.info
    GOTRUE_SITE_URL: https://agentic.staging.floorzap.info
    GOTRUE_EXTERNAL_EMAIL_ENABLED: "true"
    GOTRUE_MAILER_AUTOCONFIRM: "true"
    GOTRUE_SMTP_ADMIN_EMAIL: "your-mail@agentic.staging.floorzap.info"
    GOTRUE_SMTP_HOST: "smtp.agentic.staging.floorzap.info"
    GOTRUE_SMTP_PORT: "587"
    GOTRUE_SMTP_SENDER_NAME: "your-mail@agentic.staging.floorzap.info"
    DB_USER: supabase_admin
    DB_DRIVER: postgres
    DB_PORT: 5432
    DB_SSL: disable
  serviceAccount:
    create: true
  service:
    type: ClusterIP
    port: 9001
  autoscaling:
    enabled: false

rest:
  enabled: true
  image:
    repository: postgrest/postgrest
    pullPolicy: IfNotPresent
    tag: "latest"
  environment:
    DB_USER: supabase_admin
    DB_SSL: disable
    DB_PORT: 5432
    DB_DRIVER: postgres
  serviceAccount:
    create: true
  service:
    type: ClusterIP
    port: 9001
  autoscaling:
    enabled: false

realtime:
  enabled: true
  image:
    repository: supabase/realtime
    pullPolicy: IfNotPresent
    tag: "latest"
  environment:
    DB_USER: supabase_admin
    DB_SSL: false
    DB_PORT: 5432
    DB_DRIVER: postgres
    APP_NAME: realtime
    DB_AFTER_CONNECT_QUERY: "SET search_path TO _realtime"
    DB_ENC_KEY: supabaserealtime
    ERL_AFLAGS: -proto_dist inet_tcp
    DNS_NODES: "''"
    RLIMIT_NOFILE: "10000"
    SEED_SELF_HOST: "true"
    RUN_JANITOR: "true"
  livenessProbe:
    httpGet:
      path: /
      port: 4000
    initialDelaySeconds: 3
  serviceAccount:
    create: true
  service:
    type: ClusterIP
    port: 9001
  autoscaling:
    enabled: false

meta:
  enabled: true
  image:
    repository: supabase/postgres-meta
    pullPolicy: IfNotPresent
    tag: "v0.95.1"
  environment:
    DB_SSL: disable
    DB_USER: supabase_admin
    DB_PORT: 5432
  serviceAccount:
    create: true
  service:
    type: ClusterIP
    port: 9001
  autoscaling:
    enabled: false

storage:
  enabled: true
  image:
    repository: supabase/storage-api
    pullPolicy: IfNotPresent
    tag: "latest"
  environment:
    DB_USER: supabase_admin
    DB_PORT: 5432
    DB_SSL: disable
    DB_DRIVER: postgres
    REQUEST_ALLOW_X_FORWARDED_PATH: "true"
    FILE_SIZE_LIMIT: 5242880000
    STORAGE_BACKEND: file
    FILE_STORAGE_BACKEND_PATH: /var/lib/storage
    ENABLE_IMAGE_TRANSFORMATION: "true"
  livenessProbe:
    httpGet:
      path: /status
      port: 5000
    initialDelaySeconds: 3
  serviceAccount:
    create: true
  service:
    type: ClusterIP
    port: 9001
  autoscaling:
    enabled: false
  persistence:
    enabled: true
    storageClassName: "azuredisk-retain"
    annotations: {}
    size: 8Gi
    accessModes:
      - ReadWriteOnce
    class: ""

imgproxy:
  enabled: true
  image:
    repository: darthsim/imgproxy
    pullPolicy: IfNotPresent
    tag: "latest"
  environment:
    IMGPROXY_ENABLE_WEBP_DETECTION: "true"
  livenessProbe:
    exec:
      command:
        - imgproxy
        - health
    initialDelaySeconds: 3
  persistence:
    enabled: true
    storageClassName: "azuredisk-retain"
    annotations: {}
    size: 8Gi
    accessModes:
      - ReadWriteOnce
    class: ""
  serviceAccount:
    create: true
  service:
    type: ClusterIP
    port: 9001
  autoscaling:
    enabled: false

kong:
  enabled: true
  image:
    repository: kong
    tag: 2.8.1
  environment:
    KONG_DATABASE: "off"
    KONG_DECLARATIVE_CONFIG: /usr/local/kong/kong.yml
    KONG_LOG_LEVEL: info
  serviceAccount:
    create: true
  service:
    type: ClusterIP
    port: 9001
  autoscaling:
    enabled: false
  ingress:
    enabled: true
    className: "nginx"
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
      cert-manager.io/cluster-issuer: letsencrypt
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    tls:
      - secretName: supabase-tls
        hosts:
          - agentic.staging.floorzap.info
    hosts:
      - host: agentic.staging.floorzap.info
        paths:
          - path: /
            pathType: Prefix

analytics:
  enabled: true
  image:
    repository: supabase/logflare
    pullPolicy: IfNotPresent
    tag: "1.27.3"
  environment:
    DB_USERNAME: supabase_admin
    DB_PORT: 5432
    DB_DRIVER: postgres
    DB_SCHEMA: _analytics
    DB_DATABASE: _supabase
    FEATURE_FLAG_OVERRIDE: multibackend=true
    LOGFLARE_SINGLE_TENANT: "true"
    LOGFLARE_SUPABASE_MODE: "true"
  livenessProbe:
    httpGet:
      path: /health
      port: 4000
    initialDelaySeconds: 3
  serviceAccount:
    create: true
  service:
    type: ClusterIP
    port: 9001
  autoscaling:
    enabled: false
  bigQuery:
    enabled: false

vector:
  enabled: true
  image:
    repository: timberio/vector
    pullPolicy: IfNotPresent
    tag: "nightly-debian"
  livenessProbe:
    httpGet:
      path: /health
      port: 9001
    initialDelaySeconds: 3
  ## Vector requires logs from the control plane to function.
  ## This is normally stored in /var/log/pods
  ## Modify these values according to your environment.
  serviceAccount:
    create: true
  service:
    type: ClusterIP
    port: 9001
  autoscaling:
    enabled: false
  volumeMounts:
    - name: pod-logs
      mountPath: /var/log/pods
  volumes:
    - name: pod-logs
      hostPath:
        path: /var/log/pods

functions:
  mainConfigMap:
    enabled: false
  enabled: true
  image:
    repository: flowfirst.azurecr.io/supabase-edge/functions
    pullPolicy: IfNotPresent
    tag: "latest"
  serviceAccount:
    create: true
  imagePullSecrets:
    - name: acr-secret
  service:
    type: ClusterIP
    port: 9001
  autoscaling:
    enabled: false

minio:
  image:
    repository: minio/minio
    pullPolicy: IfNotPresent
    tag: "latest"
  enabled: true
  serviceAccount:
    create: true
  service:
    type: ClusterIP
    port: 9001
  autoscaling:
    enabled: false
  persistence:
    enabled: true
    storageClassName: "azurefile-retain"
    annotations: {}
    size: 8Gi
    accessModes:
      - ReadWriteMany
    class: ""